/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemacondominio;

import java.awt.CardLayout;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author raiss
 */
public class AppGestao extends javax.swing.JFrame {
    
    private Condominio cadastrado;
    private byte acesso;
    /**
     * Creates new form AppGestao
     */
    CardLayout cardlayout;
    public AppGestao() {
        initComponents();
        
        cardlayout = (CardLayout)split.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        Log = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        cadastroC = new javax.swing.JButton();
        split = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        passwordEntra = new javax.swing.JPasswordField();
        labelCPFlogin = new javax.swing.JLabel();
        entrarBotao = new javax.swing.JButton();
        cadastroCondominio = new javax.swing.JPanel();
        nomeC = new javax.swing.JLabel();
        nomeAdmin = new javax.swing.JLabel();
        telAdmin = new javax.swing.JLabel();
        cpfAdmin = new javax.swing.JLabel();
        textFieldNomeCadastro = new javax.swing.JTextField();
        textFieldNomeAdCadastro = new javax.swing.JTextField();
        textFieldTelAdminCadastro = new javax.swing.JTextField();
        textFieldCpfAdminCadastro = new javax.swing.JTextField();
        cadastroCond = new javax.swing.JButton();
        PanelAdmin = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        nomeMorador = new javax.swing.JLabel();
        telMorador = new javax.swing.JLabel();
        cpfMorador = new javax.swing.JLabel();
        textFieldMoradorTel = new javax.swing.JTextField();
        textFieldMoradorNome = new javax.swing.JTextField();
        textFieldMoradorCpf = new javax.swing.JTextField();
        incluirMorador = new javax.swing.JButton();
        unidadeIncluirMorador = new javax.swing.JLabel();
        textFieldUniIncluirMorador = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        cpfExcluirMorador = new javax.swing.JLabel();
        textFieldCpfExcluirMorador = new javax.swing.JTextField();
        excluirMorador = new javax.swing.JButton();
        unidadeExcluirMorador = new javax.swing.JLabel();
        textFieldUniExcluirMorador = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        textFieldUnidade = new javax.swing.JTextField();
        labelUnidade = new javax.swing.JLabel();
        enviarUnidade = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldUnidadeExcluir = new javax.swing.JTextField();
        excluirUnidade = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        incluirVisita = new javax.swing.JPanel();
        textFieldNomeVisitante = new javax.swing.JTextField();
        nomeIncluirVisitante = new javax.swing.JLabel();
        telIncluirVisitante = new javax.swing.JLabel();
        cpfIncluirVisitante = new javax.swing.JLabel();
        textFieldTelVisitante = new javax.swing.JTextField();
        textFieldCPFVisitante = new javax.swing.JTextField();
        enviarVisitante = new javax.swing.JButton();
        excluirVisita = new javax.swing.JPanel();
        cpfExcluirVisitante = new javax.swing.JLabel();
        textFieldCPFexcluirVisitante = new javax.swing.JTextField();
        excluirVisitante = new javax.swing.JButton();
        registraVisita = new javax.swing.JPanel();
        autoriza = new javax.swing.JLabel();
        textFieldAut = new javax.swing.JTextField();
        registraVisitante = new javax.swing.JLabel();
        registraUnidade = new javax.swing.JLabel();
        dataEntrada = new javax.swing.JLabel();
        dataSaida = new javax.swing.JLabel();
        textFieldVisita = new javax.swing.JTextField();
        textFieldUni = new javax.swing.JTextField();
        registrar = new javax.swing.JButton();
        textFieldDataEntrada = new javax.swing.JTextField();
        textFieldDataSaida = new javax.swing.JTextField();
        voltarA = new javax.swing.JButton();
        registrarVisistantes = new javax.swing.JButton();
        PanelMorador = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Visitante = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        textFieldExcluirVisM = new javax.swing.JTextField();
        excluirVisM = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfAutVisM = new javax.swing.JTextField();
        tfVisVisM = new javax.swing.JTextField();
        tfUniVisM = new javax.swing.JTextField();
        tfDataEntrada = new javax.swing.JTextField();
        tfDataSaida = new javax.swing.JTextField();
        registrarVisM = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfNomeVisM = new javax.swing.JTextField();
        tfTelVisM = new javax.swing.JTextField();
        tfCpfVisM = new javax.swing.JTextField();
        incluirVisM = new javax.swing.JButton();
        Morador = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textFieldNomeVisM = new javax.swing.JTextField();
        textFieldTelVisM = new javax.swing.JTextField();
        textFieldCpfVisM = new javax.swing.JTextField();
        textFieldUniVisM = new javax.swing.JTextField();
        incluirMoradorV = new javax.swing.JButton();
        voltaMorador = new javax.swing.JButton();
        registraMorador = new javax.swing.JButton();
        PanelVisitante = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        voltarVisitante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(25, 40, 24));

        Log.setText("Log In");
        Log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        cadastroC.setText("Cadastro");
        cadastroC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Exit)
                    .addComponent(cadastroC)
                    .addComponent(Log))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(Log)
                .addGap(18, 18, 18)
                .addComponent(cadastroC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 424, Short.MAX_VALUE)
                .addComponent(Exit)
                .addGap(26, 26, 26))
        );

        jSplitPane1.setLeftComponent(jPanel3);

        split.setLayout(new java.awt.CardLayout());

        login.setBackground(new java.awt.Color(107, 203, 135));

        passwordEntra.setText("jPasswordField1");

        labelCPFlogin.setText("CPF:");

        entrarBotao.setText("Entrar");
        entrarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordEntra, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(labelCPFlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(entrarBotao)))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(labelCPFlogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordEntra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrarBotao)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        split.add(login, "login");

        cadastroCondominio.setBackground(new java.awt.Color(107, 203, 135));

        nomeC.setText("Nome do Condominio:");

        nomeAdmin.setText("Nome do Administrador(a):");

        telAdmin.setText("Telefone:");

        cpfAdmin.setText("CPF:");

        cadastroCond.setText("Cadastrar");
        cadastroCond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroCondActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroCondominioLayout = new javax.swing.GroupLayout(cadastroCondominio);
        cadastroCondominio.setLayout(cadastroCondominioLayout);
        cadastroCondominioLayout.setHorizontalGroup(
            cadastroCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroCondominioLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(cadastroCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cadastroCond, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cadastroCondominioLayout.createSequentialGroup()
                        .addGroup(cadastroCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeAdmin)
                            .addComponent(telAdmin)
                            .addComponent(nomeC)
                            .addComponent(cpfAdmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cadastroCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldNomeCadastro)
                            .addComponent(textFieldNomeAdCadastro)
                            .addComponent(textFieldTelAdminCadastro)
                            .addComponent(textFieldCpfAdminCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        cadastroCondominioLayout.setVerticalGroup(
            cadastroCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroCondominioLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(cadastroCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeC)
                    .addComponent(textFieldNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeAdmin)
                    .addComponent(textFieldNomeAdCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telAdmin)
                    .addComponent(textFieldTelAdminCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroCondominioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfAdmin)
                    .addComponent(textFieldCpfAdminCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastroCond)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        split.add(cadastroCondominio, "cadastroCondominio");

        PanelAdmin.setBackground(new java.awt.Color(107, 203, 135));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Incluir Morador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        nomeMorador.setText("Nome:");

        telMorador.setText("Telefone:");

        cpfMorador.setText("CPF:");

        incluirMorador.setText("Incluir");
        incluirMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirMoradorActionPerformed(evt);
            }
        });

        unidadeIncluirMorador.setText("Unidade");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomeMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cpfMorador, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(unidadeIncluirMorador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldMoradorNome)
                            .addComponent(textFieldMoradorCpf)
                            .addComponent(textFieldUniIncluirMorador)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(telMorador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldMoradorTel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addComponent(incluirMorador)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeMorador)
                    .addComponent(textFieldMoradorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telMorador)
                            .addComponent(textFieldMoradorTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpfMorador)
                            .addComponent(textFieldMoradorCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(incluirMorador)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unidadeIncluirMorador)
                    .addComponent(textFieldUniIncluirMorador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir Morador", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        cpfExcluirMorador.setText("CPF:");

        excluirMorador.setText("Excluir");
        excluirMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirMoradorActionPerformed(evt);
            }
        });

        unidadeExcluirMorador.setText("Unidade:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cpfExcluirMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldCpfExcluirMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(unidadeExcluirMorador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldUniExcluirMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(excluirMorador)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfExcluirMorador)
                    .addComponent(textFieldCpfExcluirMorador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unidadeExcluirMorador)
                    .addComponent(textFieldUniExcluirMorador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(excluirMorador)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        jTabbedPane1.addTab("Morador", jPanel4);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Incluir Unidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        labelUnidade.setText("Número da Unidade:");

        enviarUnidade.setText("Enviar");
        enviarUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarUnidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(labelUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(enviarUnidade))
                .addGap(160, 160, 160))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUnidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enviarUnidade)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir Unidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("Número da Unidade:");

        excluirUnidade.setText("Excluir");
        excluirUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirUnidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(excluirUnidade)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldUnidadeExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldUnidadeExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excluirUnidade)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Unidade", jPanel2);

        incluirVisita.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Incluir Visitante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        textFieldNomeVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeVisitanteActionPerformed(evt);
            }
        });

        nomeIncluirVisitante.setText("Nome:");

        telIncluirVisitante.setText("Telefone:");

        cpfIncluirVisitante.setText("CPF:");

        enviarVisitante.setText("Enviar");
        enviarVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarVisitanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout incluirVisitaLayout = new javax.swing.GroupLayout(incluirVisita);
        incluirVisita.setLayout(incluirVisitaLayout);
        incluirVisitaLayout.setHorizontalGroup(
            incluirVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incluirVisitaLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(incluirVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cpfIncluirVisitante)
                    .addComponent(nomeIncluirVisitante)
                    .addComponent(telIncluirVisitante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incluirVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldNomeVisitante)
                    .addComponent(textFieldTelVisitante)
                    .addComponent(textFieldCPFVisitante, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enviarVisitante)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        incluirVisitaLayout.setVerticalGroup(
            incluirVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incluirVisitaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(incluirVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNomeVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeIncluirVisitante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incluirVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldTelVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telIncluirVisitante)
                    .addComponent(enviarVisitante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incluirVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCPFVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfIncluirVisitante))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        excluirVisita.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir Visitante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        cpfExcluirVisitante.setText("CPF:");

        excluirVisitante.setText("Excluir");
        excluirVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirVisitanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout excluirVisitaLayout = new javax.swing.GroupLayout(excluirVisita);
        excluirVisita.setLayout(excluirVisitaLayout);
        excluirVisitaLayout.setHorizontalGroup(
            excluirVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(excluirVisitaLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(cpfExcluirVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCPFexcluirVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(excluirVisitante)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        excluirVisitaLayout.setVerticalGroup(
            excluirVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(excluirVisitaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(excluirVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfExcluirVisitante)
                    .addComponent(textFieldCPFexcluirVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluirVisitante))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        registraVisita.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Visitante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        autoriza.setText("Autorização:");

        textFieldAut.setToolTipText("");

        registraVisitante.setText("Visitante:");

        registraUnidade.setText("Unidade:");

        dataEntrada.setText("Data de Entrada:");

        dataSaida.setText("Data de Saida:");

        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registraVisitaLayout = new javax.swing.GroupLayout(registraVisita);
        registraVisita.setLayout(registraVisitaLayout);
        registraVisitaLayout.setHorizontalGroup(
            registraVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registraVisitaLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(registraVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registraVisitaLayout.createSequentialGroup()
                        .addGroup(registraVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(registraUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(registraVisitante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(autoriza, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registraVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldUni)
                            .addComponent(textFieldVisita)
                            .addComponent(textFieldAut)))
                    .addGroup(registraVisitaLayout.createSequentialGroup()
                        .addGroup(registraVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dataSaida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dataEntrada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registraVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldDataSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(textFieldDataEntrada))))
                .addGap(108, 108, 108)
                .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        registraVisitaLayout.setVerticalGroup(
            registraVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registraVisitaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(registraVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoriza)
                    .addComponent(textFieldAut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registraVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registraVisitante)
                    .addComponent(textFieldVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registraVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registraUnidade)
                    .addComponent(textFieldUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registraVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataEntrada)
                    .addComponent(textFieldDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registraVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataSaida)
                    .addComponent(registrar)
                    .addComponent(textFieldDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registraVisita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(incluirVisita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(excluirVisita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(incluirVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(excluirVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registraVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Visitante", jPanel1);

        voltarA.setText("Log Out");
        voltarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarAActionPerformed(evt);
            }
        });

        registrarVisistantes.setText("Registrar Visitantes");
        registrarVisistantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarVisistantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAdminLayout = new javax.swing.GroupLayout(PanelAdmin);
        PanelAdmin.setLayout(PanelAdminLayout);
        PanelAdminLayout.setHorizontalGroup(
            PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PanelAdminLayout.createSequentialGroup()
                        .addComponent(registrarVisistantes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltarA))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        PanelAdminLayout.setVerticalGroup(
            PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAdminLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarA)
                    .addComponent(registrarVisistantes))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        split.add(PanelAdmin, "PanelAdmin");

        PanelMorador.setBackground(new java.awt.Color(107, 203, 135));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir Visitante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        jLabel9.setText("CPF:");

        excluirVisM.setText("Excluir");
        excluirVisM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirVisMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldExcluirVisM, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(excluirVisM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textFieldExcluirVisM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluirVisM))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Visitante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        jLabel13.setText("Autorização:");

        jLabel14.setText("Visitante:");

        jLabel15.setText("Unidade:");

        jLabel16.setText("Data de Entrada:");

        jLabel17.setText("Data de Saida:");

        registrarVisM.setText("Registrar");
        registrarVisM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarVisMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(tfDataSaida))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAutVisM))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfVisVisM)
                            .addComponent(tfUniVisM)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(registrarVisM)
                .addGap(81, 81, 81))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfAutVisM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(tfVisVisM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfUniVisM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tfDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrarVisM))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Incluir Visitante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        jLabel10.setText("Nome:");

        jLabel11.setText("Telefone:");

        jLabel12.setText("CPF:");

        incluirVisM.setText("Incluir");
        incluirVisM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirVisMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfCpfVisM))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTelVisM))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNomeVisM, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(incluirVisM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfNomeVisM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfTelVisM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incluirVisM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfCpfVisM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout VisitanteLayout = new javax.swing.GroupLayout(Visitante);
        Visitante.setLayout(VisitanteLayout);
        VisitanteLayout.setHorizontalGroup(
            VisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VisitanteLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(VisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        VisitanteLayout.setVerticalGroup(
            VisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VisitanteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jTabbedPane2.addTab("Visitante", Visitante);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Incluir Morador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        jLabel5.setText("Nome:");

        jLabel6.setText("Telefone:");

        jLabel7.setText("CPF:");

        jLabel8.setText("Unidade:");

        textFieldNomeVisM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeVisMActionPerformed(evt);
            }
        });

        incluirMoradorV.setText("Incluir");
        incluirMoradorV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirMoradorVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(textFieldTelVisM, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(textFieldCpfVisM)
                                .addComponent(textFieldUniVisM)))
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(textFieldNomeVisM, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(incluirMoradorV, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textFieldNomeVisM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textFieldTelVisM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textFieldCpfVisM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textFieldUniVisM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(incluirMoradorV)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MoradorLayout = new javax.swing.GroupLayout(Morador);
        Morador.setLayout(MoradorLayout);
        MoradorLayout.setHorizontalGroup(
            MoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MoradorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        MoradorLayout.setVerticalGroup(
            MoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MoradorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Morador", Morador);

        voltaMorador.setText("Log Out");
        voltaMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltaMoradorActionPerformed(evt);
            }
        });

        registraMorador.setText("Registrar Visitante");
        registraMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraMoradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMoradorLayout = new javax.swing.GroupLayout(PanelMorador);
        PanelMorador.setLayout(PanelMoradorLayout);
        PanelMoradorLayout.setHorizontalGroup(
            PanelMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMoradorLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(PanelMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PanelMoradorLayout.createSequentialGroup()
                        .addComponent(registraMorador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltaMorador))
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        PanelMoradorLayout.setVerticalGroup(
            PanelMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMoradorLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltaMorador)
                    .addComponent(registraMorador))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        split.add(PanelMorador, "PanelMorador");

        PanelVisitante.setBackground(new java.awt.Color(107, 203, 135));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Bem Vindo, Visitante");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Você não possui autorização para mudar os dados");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("para este condomínio.");

        voltarVisitante.setText("Log Out");
        voltarVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarVisitanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(65, 65, 65))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel2))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(voltarVisitante)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel2)
                .addGap(65, 65, 65)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(49, 49, 49)
                .addComponent(voltarVisitante)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Visitante", jPanel9);

        javax.swing.GroupLayout PanelVisitanteLayout = new javax.swing.GroupLayout(PanelVisitante);
        PanelVisitante.setLayout(PanelVisitanteLayout);
        PanelVisitanteLayout.setHorizontalGroup(
            PanelVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVisitanteLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        PanelVisitanteLayout.setVerticalGroup(
            PanelVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVisitanteLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        split.add(PanelVisitante, "PanelVisitante");

        jSplitPane1.setRightComponent(split);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void LogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogActionPerformed
        cardlayout.show(split, "login");
    }//GEN-LAST:event_LogActionPerformed

    private void cadastroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroCActionPerformed
        cardlayout.show(split, "cadastroCondominio");
    }//GEN-LAST:event_cadastroCActionPerformed

    private void entrarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarBotaoActionPerformed

        char[] password = passwordEntra.getPassword();
        String pass = new String(password);
   
        
        if(this.cadastrado == null){
            JOptionPane.showMessageDialog(null, "Condominio não cadastrado");
        }else{
            if(this.cadastrado.encontraAdmin(pass)){
                cardlayout.show(split, "PanelAdmin");
                cadastroC.setVisible(false);
                Log.setVisible(false);
                this.acesso = 2;
                JOptionPane.showMessageDialog(null, "Admin");
            }
            
            if(this.cadastrado.encontraMorador(pass)){
                cardlayout.show(split, "PanelMorador");
                Log.setVisible(false);
                cadastroC.setVisible(false);
                this.acesso = 1;
                JOptionPane.showMessageDialog(null, "Morador");
            }
            
            if(this.cadastrado.encontraVisitante(pass)){
                cardlayout.show(split, "PanelVisitante");
                Log.setVisible(false);
                cadastroC.setVisible(false);
                this.acesso = 0;
                JOptionPane.showMessageDialog(null, "Visitante");
            }
        }
        
    }//GEN-LAST:event_entrarBotaoActionPerformed

    private void cadastroCondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroCondActionPerformed
        Pessoa n = new Administrador(textFieldNomeAdCadastro.getText(), textFieldTelAdminCadastro.getText(), textFieldCpfAdminCadastro.getText());
        this.cadastrado = new Condominio(textFieldNomeCadastro.getText(), n);
        
        if(this.cadastrado.salvou(n)){
            JOptionPane.showMessageDialog(null, "Salvo.");
        }else{
            JOptionPane.showMessageDialog(null, "Tente novamente.");
        }
        System.out.println(this.cadastrado.toString());
    }//GEN-LAST:event_cadastroCondActionPerformed

    private void enviarUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarUnidadeActionPerformed
        
        String unidade = textFieldUnidade.getText();
        short u = Short.parseShort(unidade);
        Unidade uni = new Unidade(u);
        
        if(this.cadastrado.incluirUnidade(uni) == false){
            JOptionPane.showMessageDialog(null, "Unidade já existe");
        }
        
        this.cadastrado.pritnUni();
        
        
    }//GEN-LAST:event_enviarUnidadeActionPerformed

    private void excluirUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirUnidadeActionPerformed
        
        String unidade = textFieldUnidade.getText();
        short u = Short.parseShort(unidade);
        
        this.cadastrado.excluirUnidade(u);
        
    }//GEN-LAST:event_excluirUnidadeActionPerformed

    private void textFieldNomeVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeVisitanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomeVisitanteActionPerformed

    private void enviarVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarVisitanteActionPerformed
        
        Visitante visi = new Visitante(textFieldNomeVisitante.getText(), textFieldTelVisitante.getText(), textFieldCPFVisitante.getText());
        
        if(this.cadastrado.incluirVisitante(visi) == false){
            JOptionPane.showMessageDialog(null, "Visitante já existe");
        }
        
        this.cadastrado.printV();
        
    }//GEN-LAST:event_enviarVisitanteActionPerformed

    private void excluirVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirVisitanteActionPerformed
        
        String cpf = textFieldCPFexcluirVisitante.getText();
        
        this.cadastrado.excluirVisitante(cpf);
    }//GEN-LAST:event_excluirVisitanteActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        
        String morador = textFieldAut.getText();
        String visitante = textFieldVisita.getText();
        short u = Short.parseShort(textFieldUni.getText());
        
        String datae = textFieldDataEntrada.getText();
        String[] partes = datae.split("/");
        String dia = partes[0];
        String mes = partes[1];
        String ano = partes[2];
        Data entrada = new Data(Byte.parseByte(dia),Byte.parseByte(mes),Short.parseShort(ano)); 
        
        String datas = textFieldDataSaida.getText();
        String[] parts = datas.split("/");
        String diaS = parts[0];
        String mesS = parts[1];
        String anoS = parts[2];
        Data saida = new Data(Byte.parseByte(diaS),Byte.parseByte(mesS),Short.parseShort(anoS));
        
        this.cadastrado.registrarVisitante(this.cadastrado.getPessoa(morador, this.acesso),this.cadastrado.getVisitante(visitante), this.cadastrado.getUnidades(u), entrada, saida);
        
        this.cadastrado.printRegistro();
    }//GEN-LAST:event_registrarActionPerformed

    private void incluirMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirMoradorActionPerformed
        
        Unidade u;
        short uni = Short.parseShort(textFieldUniIncluirMorador.getText());
        Condomino novo;
        
        if(this.cadastrado.getUnidades(uni) == null){
            JOptionPane.showMessageDialog(null, "Não existe essa unidade.");
        }else{
            u = this.cadastrado.getUnidades(uni);
            novo = new Condomino(textFieldMoradorNome.getText(), textFieldMoradorTel.getText(), textFieldMoradorCpf.getText());
            u.incluirMorador(novo);
            this.cadastrado.pritnUni();
        }
        
    }//GEN-LAST:event_incluirMoradorActionPerformed

    private void excluirMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirMoradorActionPerformed
        
        Unidade u;
        short uni = Short.parseShort(textFieldUniExcluirMorador.getText());
        if(this.cadastrado.getUnidades(uni) == null){
            JOptionPane.showMessageDialog(null, "Não existe essa unidade.");
        }else{
            u = this.cadastrado.getUnidades(uni);
            u.excluirMorador(textFieldCpfExcluirMorador.getText());
        }
        
    }//GEN-LAST:event_excluirMoradorActionPerformed

    private void textFieldNomeVisMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeVisMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomeVisMActionPerformed

    private void incluirMoradorVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirMoradorVActionPerformed

        Unidade u;
        short uni = Short.parseShort(textFieldUniVisM.getText());
        Condomino novo;
        
        if(this.cadastrado.getUnidades(uni) == null){
            JOptionPane.showMessageDialog(null, "Não existe essa unidade.");
        }else{
            u = this.cadastrado.getUnidades(uni);
            novo = new Condomino(textFieldNomeVisM.getText(), textFieldTelVisM.getText(), textFieldCpfVisM.getText());
            u.incluirMorador(novo);
            this.cadastrado.pritnUni();
        }
        
        
    }//GEN-LAST:event_incluirMoradorVActionPerformed

    private void excluirVisMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirVisMActionPerformed
        String cpf = textFieldExcluirVisM.getText();
        
        this.cadastrado.excluirVisitante(cpf);
    }//GEN-LAST:event_excluirVisMActionPerformed

    private void incluirVisMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirVisMActionPerformed
        Visitante visi = new Visitante(tfNomeVisM.getText(), tfTelVisM.getText(), tfCpfVisM.getText());
        
        if(this.cadastrado.incluirVisitante(visi) == false){
            JOptionPane.showMessageDialog(null, "Visitante já existe");
        }
        
        this.cadastrado.printV();
    }//GEN-LAST:event_incluirVisMActionPerformed

    private void registrarVisMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarVisMActionPerformed
        
        String morador = tfAutVisM.getText();
        String visitante = tfVisVisM.getText();
        short u = Short.parseShort(tfUniVisM.getText());
        
        String datae = tfDataEntrada.getText();
        String[] partes = datae.split("/");
        String dia = partes[0];
        String mes = partes[1];
        String ano = partes[2];
        Data entrada = new Data(Byte.parseByte(dia),Byte.parseByte(mes),Short.parseShort(ano)); 
        
        String datas = tfDataSaida.getText();
        String[] parts = datas.split("/");
        String diaS = parts[0];
        String mesS = parts[1];
        String anoS = parts[2];
        Data saida = new Data(Byte.parseByte(diaS),Byte.parseByte(mesS),Short.parseShort(anoS));
        
        this.cadastrado.registrarVisitante(this.cadastrado.getPessoa(morador, this.acesso),this.cadastrado.getVisitante(visitante), this.cadastrado.getUnidades(u), entrada, saida);
        
        this.cadastrado.printRegistro();
        
    }//GEN-LAST:event_registrarVisMActionPerformed

    private void voltarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarAActionPerformed
        
        cardlayout.show(split, "login");
        Log.setVisible(true);
        cadastroC.setVisible(true);

    }//GEN-LAST:event_voltarAActionPerformed

    private void registrarVisistantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarVisistantesActionPerformed
        
        File registro= new File("RegistroVisitantes.txt");
        try {
            this.cadastrado.gravaRegistro(registro);
            JOptionPane.showMessageDialog(null, "Concluido.");
        } catch (IOException ex) {
            Logger.getLogger(AppGestao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_registrarVisistantesActionPerformed

    private void voltaMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltaMoradorActionPerformed
        cardlayout.show(split, "login");
        Log.setVisible(true);
        cadastroC.setVisible(true);
    }//GEN-LAST:event_voltaMoradorActionPerformed

    private void registraMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraMoradorActionPerformed
        File registro= new File("RegistroVisitantes.txt");
        try {
            this.cadastrado.gravaRegistro(registro);
            JOptionPane.showMessageDialog(null, "Concluido.");
        } catch (IOException ex) {
            Logger.getLogger(AppGestao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_registraMoradorActionPerformed

    private void voltarVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarVisitanteActionPerformed
        cardlayout.show(split, "login");
        Log.setVisible(true);
        cadastroC.setVisible(true);
    }//GEN-LAST:event_voltarVisitanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppGestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppGestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppGestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppGestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppGestao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Log;
    private javax.swing.JPanel Morador;
    private javax.swing.JPanel PanelAdmin;
    private javax.swing.JPanel PanelMorador;
    private javax.swing.JPanel PanelVisitante;
    private javax.swing.JPanel Visitante;
    private javax.swing.JLabel autoriza;
    private javax.swing.JButton cadastroC;
    private javax.swing.JButton cadastroCond;
    private javax.swing.JPanel cadastroCondominio;
    private javax.swing.JLabel cpfAdmin;
    private javax.swing.JLabel cpfExcluirMorador;
    private javax.swing.JLabel cpfExcluirVisitante;
    private javax.swing.JLabel cpfIncluirVisitante;
    private javax.swing.JLabel cpfMorador;
    private javax.swing.JLabel dataEntrada;
    private javax.swing.JLabel dataSaida;
    private javax.swing.JButton entrarBotao;
    private javax.swing.JButton enviarUnidade;
    private javax.swing.JButton enviarVisitante;
    private javax.swing.JButton excluirMorador;
    private javax.swing.JButton excluirUnidade;
    private javax.swing.JButton excluirVisM;
    private javax.swing.JPanel excluirVisita;
    private javax.swing.JButton excluirVisitante;
    private javax.swing.JButton incluirMorador;
    private javax.swing.JButton incluirMoradorV;
    private javax.swing.JButton incluirVisM;
    private javax.swing.JPanel incluirVisita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel labelCPFlogin;
    private javax.swing.JLabel labelUnidade;
    private javax.swing.JPanel login;
    private javax.swing.JLabel nomeAdmin;
    private javax.swing.JLabel nomeC;
    private javax.swing.JLabel nomeIncluirVisitante;
    private javax.swing.JLabel nomeMorador;
    private javax.swing.JPasswordField passwordEntra;
    private javax.swing.JButton registraMorador;
    private javax.swing.JLabel registraUnidade;
    private javax.swing.JPanel registraVisita;
    private javax.swing.JLabel registraVisitante;
    private javax.swing.JButton registrar;
    private javax.swing.JButton registrarVisM;
    private javax.swing.JButton registrarVisistantes;
    private javax.swing.JPanel split;
    private javax.swing.JLabel telAdmin;
    private javax.swing.JLabel telIncluirVisitante;
    private javax.swing.JLabel telMorador;
    private javax.swing.JTextField textFieldAut;
    private javax.swing.JTextField textFieldCPFVisitante;
    private javax.swing.JTextField textFieldCPFexcluirVisitante;
    private javax.swing.JTextField textFieldCpfAdminCadastro;
    private javax.swing.JTextField textFieldCpfExcluirMorador;
    private javax.swing.JTextField textFieldCpfVisM;
    private javax.swing.JTextField textFieldDataEntrada;
    private javax.swing.JTextField textFieldDataSaida;
    private javax.swing.JTextField textFieldExcluirVisM;
    private javax.swing.JTextField textFieldMoradorCpf;
    private javax.swing.JTextField textFieldMoradorNome;
    private javax.swing.JTextField textFieldMoradorTel;
    private javax.swing.JTextField textFieldNomeAdCadastro;
    private javax.swing.JTextField textFieldNomeCadastro;
    private javax.swing.JTextField textFieldNomeVisM;
    private javax.swing.JTextField textFieldNomeVisitante;
    private javax.swing.JTextField textFieldTelAdminCadastro;
    private javax.swing.JTextField textFieldTelVisM;
    private javax.swing.JTextField textFieldTelVisitante;
    private javax.swing.JTextField textFieldUni;
    private javax.swing.JTextField textFieldUniExcluirMorador;
    private javax.swing.JTextField textFieldUniIncluirMorador;
    private javax.swing.JTextField textFieldUniVisM;
    private javax.swing.JTextField textFieldUnidade;
    private javax.swing.JTextField textFieldUnidadeExcluir;
    private javax.swing.JTextField textFieldVisita;
    private javax.swing.JTextField tfAutVisM;
    private javax.swing.JTextField tfCpfVisM;
    private javax.swing.JTextField tfDataEntrada;
    private javax.swing.JTextField tfDataSaida;
    private javax.swing.JTextField tfNomeVisM;
    private javax.swing.JTextField tfTelVisM;
    private javax.swing.JTextField tfUniVisM;
    private javax.swing.JTextField tfVisVisM;
    private javax.swing.JLabel unidadeExcluirMorador;
    private javax.swing.JLabel unidadeIncluirMorador;
    private javax.swing.JButton voltaMorador;
    private javax.swing.JButton voltarA;
    private javax.swing.JButton voltarVisitante;
    // End of variables declaration//GEN-END:variables
}
